server:
  port: 8082

spring:
  application:
    name: bc02-fleet-management
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:h2:mem:fleet;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
