server:
  port: 8090

spring:
  application:
    name: fleet-service

  datasource:
    url: jdbc:h2:mem:fleet;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    enabled: false